name: "The Tech Auto-Pilot"

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias às 00:00
  workflow_dispatch: # Permite-te carregar num botão para executar agora

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Descarregar o código)
        uses: actions/checkout@v4
        with:
          submodules: true  # Importante para o tema
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências do Python
        run: |
          pip install pandas deep-translator fpdf2

      - name: Correr o Processador de Artigos
        run: python scripts/processor.py

      - name: Instalar o Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build do Site
        run: hugo --minify

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
